### ISSUE TITLE
The source path doesn't exists

### ISSUE THREAD

**Issue by joshuamataaraya** [sunwukonga/docker-expo#1]
Getting this error in the step of running the .sh file

C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Mount denied:
The source path "C:/git/docker-expo/BBB;C"
doesn't exist and is not known to Docker.

**Comment by sunwukonga** [comment]
You're obviously using Windows, and I use Linux, so I may not have an insight for you.

However, the problem will be that the `.sh` file is accessing variables that don't exist, AND paths that don't exist.

As it exists in the `.sh` file, the relevant command is:
```
docker run \
       --rm \
       -it \
       --user="$UID" \
       --privileged \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v /dev/bus/usb:/dev/bus/usb \
       -v /home/$USER/.android:/home/dev/.android \
       -v $(pwd):/home/dev/app \
       --net host \
       -e DISPLAY="$DISPLAY" \
       --name $CONTAINER_NAME \
       expo /bin/bash
```

I suggest deleting the following lines:
```
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v /dev/bus/usb:/dev/bus/usb \
       -v /home/$USER/.android:/home/dev/.android \
```
and hard wiring the BBB directory from:
```
       -v $(pwd):/home/dev/app \
```
to
```
       -v C:/git/docker-expo/BBB:/home/dev/app \
```
If you need your USB attached, replace:
```
       -v /dev/bus/usb:/dev/bus/usb \
```
with
```
       -v d:/:/dev/bus/usb \
```
Where `d:/` refers to your usb drive letter.
If you want to hook your .android directory up, you should be able to work that out from the preceding.

I have no way of testing this, so take the above with a grain of salt. You'd be wise to `echo` or otherwise debug the values you are getting for $UID and $DISPLAY, but they may not be a problem.

**Comment by sunwukonga** [comment]
If you do decide to use the USB (only relevant if you are using the USB to connect to your phone directly), you'll probably need to share your USB through docker. Instructions at https://docs.sevenbridges.com/docs/mount-a-usb-drive-in-a-docker-container

**Comment by joshuamataaraya** [comment]
Thanks @sunwukonga  closing this as it's not for windows. I'm so new with containers.
